### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by boatt** [550609334/Twobbble#2]
FATAL EXCEPTION: main
                                                              Process: com.twobbble, PID: 16159
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twobbble/com.twobbble.view.activity.MainActivity}: android.view.InflateException: Binary XML file line #28: Error inflating class android.support.design.widget.NavigationView
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2548)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607)
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:174)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:146)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5756)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                               Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class android.support.design.widget.NavigationView
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                  at com.twobbble.view.activity.MainActivity.onCreate(MainActivity.kt:40)
                                                                  at android.app.Activity.performCreate(Activity.java:5619)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2512)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:174) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:146) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5756) 
                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                  at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:600)
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                  at com.twobbble.view.activity.MainActivity.onCreate(MainActivity.kt:40) 
                                                                  at android.app.Activity.performCreate(Activity.java:5619) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2512) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:174) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:146) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5756) 
                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                               Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class ImageButton
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                  at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:211)
                                                                  at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:269)
                                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:178)
                                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:100)
                                                                  at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                  at com.twobbble.view.activity.MainActivity.onCreate(MainActivity.kt:40) 
                                                                  at android.app.Activity.performCreate(Activity.java:5619) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2512) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:174) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:146) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5756) 
                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                               Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x10302ae a=2 r=0x10302ae}
                                                                  at android.content.res.Resources.loadDrawable(Resources.java:3429)
                                                                  at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                  at android.view.View.<init>(View.java:3760)
                                                              	at android.widget.ImageView.<init>(ImageView.ja

**Comment by liuzipengWally** [comment]
是最新代码吗？ 最新代码已经解决这个问题，这是之前不小心删了style的parent

**Comment by boatt** [comment]
是的,是今天早上下载的,最之前是编译不通过错误描述和#1是一样的,然后我注释了BetaActivity清单文件的android:theme="@style/DialogActivityTheme2"这行代码,运行就报错了,设备是三星4.4.4

**Comment by liuzipengWally** [comment]
我知道了 这个是bugly的检查更新最近出现的问题，用自定义主题就会出错，我更新代码
